repos:
-   repo: local
    hooks:
    - id: black
      name: black
      entry: black
      language: python
      types: [python]
    - id: flake8
      name: flake8
      entry: flake8
      language: python
      types: [ python ]
      args: ["--config=setup.cfg"]
    - id: isort
      name: isort
      entry: isort
      language: python
      types: [python]
      args: ["--profile", "black"]