version: '3.6'
services:
  redis:
    image: "redis:alpine"
    hostname: redis
    expose:
      - "6379"
    networks:
      - apinet
  fastapi:
    build: ./fastapi-solution/src
    depends_on:
      - redis
    env_file:
      - fastapi-solution/src/core/.dev.env
    expose:
      - "8000"
    networks:
      - apinet
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./config:/etc/nginx/conf.d:ro
    depends_on:
      - fastapi
    ports:
      - "80:80"
    networks:
      - apinet

networks:
  apinet:
    external:
      name: api_network