version: '3.6'
services:
  redis:
    image: "redis:alpine"
    hostname: redis
    ports:
      - "6379:6379"
    networks:
      - apinet
  fastapi:
    build: ./fastapi-solution/src
    depends_on:
      - redis
    env_file:
      - fastapi-solution/src/core/.dev.env
    ports:
      - "8000:8000"
    networks:
      - apinet

networks:
  apinet:
    external:
      name: api_network