PAGE_NOT_FOUND = "page not found"
FILM_BY_GENRE_NOT_FOUND = "no film with this genre was found"
PERSON_NOT_FOUND = "person not found"
FILM_NOT_FOUND = "film not found"
GENRE_NOT_FOUND = "genre not found"
BAD_SORTING_FORMAT = "incorrect sorting format"
TOKEN_OUTDATED = "token outdated"
WRONG_PERMISSION = "wrong permission user"
