name: Проверка
on: [push]
jobs:
  linter:
    name: Линтер
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Установка Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.0
      - name: Установка зависимостей
        run: |
          python -m pip install --upgrade pip
          pip install flake8==5.0.4 black==22.6.0 isort==5.10.1
      - name: Flake8
        run: flake8